name: 聚看点
 
on:
  workflow_dispatch:
  schedule:
     - cron: '0,20 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JKD_COOKIE: ${{ secrets.JKD_COOKIE }}
        JKD_WITHDRAW: ${{ secrets.JKD_WITHDRAW }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/shylocks/Loon.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm config set package-lock false
          npm install
      - name: 运行 【聚看点】
        if: env.JKD_COOKIE
        run: |
          cd ~/Scripts
          node jkd.js
        env:
          BARK_PUSH: ${{ secrets.BARK_PUSH || github.event.client_payload.BARK_PUSH }}
