name: 企鹅读书2

on:
  workflow_dispatch:
  schedule:
    - cron: '* */6 * * *'
  watch:
    type: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Setup Debug Session
        uses: P3TERX/debugger-action@main

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行【企鹅读书】' 
        run: ./run.sh
        env:
            CONFIG: ${{ secrets.CONFIG }}
