name: Proxy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  watch:
    type: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: run
      run: cat  /proc/sys/net/ipv4/ip_forward
    - name: run
      env: 
        V2RAY_CNF: ${{ secrets.V2RAY_CNF }}
      run: echo $V2RAY_CNF > config.json && docker run -d --restart=always --name=v2ray -p2333:2333 -v $PWD/config.json:/etc/v2ray/config.json v2fly/v2fly-core
    - name: frp
      env: 
        FRP_CNF: ${{ secrets.FRPC_CNF }}
      run:  wget https://github.com/fatedier/frp/releases/download/v0.34.3/frp_0.34.3_linux_amd64.tar.gz && tar xvf frp_0.34.3_linux_amd64.tar.gz && cd frp_0.34.3_linux_amd64 && echo "$FRP_CNF" > frpc.ini && ./frpc -c ./frpc.ini
